config/routes.rb
Rails.application.routes.draw do
  
  resources :articles
  get root 'pages#home'
  get 'about',to: 'pages#about'
  
  
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence:true, length:{minimum:2, maximum:30 }
    validates :description, presence:true, length:{minimum:2, maximum:150 }
    
  
end  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController<ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  
  def index
    @articles=Article.all
  end  
  
  def new
    @article=Article.new
  end 
  def create
    #render plain: params[:article].inspect
    @article=Article.new(article_params)
    if @article.save
      flash[:notice]="article wass created succesfuly"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  
  def show

  end
  
  def edit


  end  
  
  def update

    if @article.update(article_params)
      flash[:notice]="article wass updateed succesfuly"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end  
  
  def destroy

    @article.destroy
    flash[:notice] = "article deleted"
    redirect_to articles_path
  end  
  
  private
    def set_article
      @article=Article.find(params[:id])
    end  
  
    def article_params
      params.require(:article).permit(:title, :description)
    end  
end  

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    
  end
  
  def about
    
  end
  
end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2>the following errors had occured</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
    
    
  </p>

<% end %>

<%= link_to "listing", articles_path %>

app/views/articles/edit.html.erb
<h2>editing the selected article</h2>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>listing all articles</h1>
<p>
  <%= link_to "create new article", new_article_path %>
</p>


  <table>
    <tr>
      <td>
        <strong>title</strong>
      </td>
      <td>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      </td>
      <td>
        <strong>description</strong>
      </td>
    </tr>
<% @articles.each do |article| %>
    <tr>
      <td>
        <%= article.title %>
      </td>
      <td>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      </td>
      <td>
        <%= article.description %>
      </td>
      <td>
        <%= link_to "edit", edit_article_path(article) %>
      </td>
      <td>
        <%= link_to "show", article_path(article) %>
      </td>
      <td>
        <%= link_to "delete", article_path(article), method: :delete, data: {confirm: "Are u sure?"}  %>
      </td>
    </tr>
    <% end %>
  </table>

app/views/articles/new.html.erb
<h1> create new articel</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<%= render 'layouts/messages' %>
<h1>showing selected article</h1>

<p> 
  Title: <%= @article.title %> </br></br>
  
  Description: <%= @article.description %> 
</p>
<%= link_to "listing", articles_path %>

app/views/layouts/_messages.html.erb
 <ul>
  <% flash.each do |name,msg| %>
    <li> <%= msg %></li>
  <% end %> 
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>this is the aboutpage</h1>
<br>
<%= link_to "home", root_path %>

app/views/pages/home.html.erb
<h1>this is the homepage</h1>
<br>
<%= link_to "alpha-blog", articles_path %> | <%= link_to "about", about_path %>